package main
var MockAuthLog = []map[string]interface{}{
	{
		"service":    "auth-service",
		"level":      "INFO",
		"message":    "User login successful",
		"request_id": "req-001",
		"user_id":    "user-101",
		"ip":         "192.168.1.10",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "WARN",
		"message":    "Invalid password attempt",
		"request_id": "req-002",
		"user_id":    "user-101",
		"ip":         "192.168.1.10",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "ERROR",
		"message":    "Account locked due to too many failed attempts",
		"request_id": "req-003",
		"user_id":    "user-101",
		"ip":         "192.168.1.10",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "INFO",
		"message":    "Token refreshed successfully",
		"request_id": "req-004",
		"user_id":    "user-202",
		"ip":         "10.0.0.5",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "WARN",
		"message":    "User not found during login",
		"request_id": "req-005",
		"user_id":    "unknown",
		"ip":         "172.16.0.3",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "DEBUG",
		"message":    "Password validation started",
		"request_id": "req-006",
		"user_id":    "user-202",
		"ip":         "10.0.0.5",
		"timestamp":  "",
	},
	{
		"service":    "auth-service",
		"level":      "ERROR",
		"message":    "Suspicious login activity detected",
		"request_id": "req-007",
		"user_id":    "user-303",
		"ip":         "203.0.113.99",
		"timestamp":  "",
	},
}
