package main

var MockAuthLog = []map[string]interface{}{
	{
		"service":   "auth-service",
		"level":     "INFO",
		"message":   "User login successful",
		"requestId": "req-001",
		"userId":    "user-101",
		"ip":        "192.168.1.10",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "WARN",
		"message":   "Invalid password attempt",
		"requestId": "req-002",
		"userId":    "user-101",
		"ip":        "192.168.1.10",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "ERROR",
		"message":   "Account locked due to too many failed attempts",
		"requestId": "req-003",
		"userId":    "user-101",
		"ip":        "192.168.1.10",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "INFO",
		"message":   "Token refreshed successfully",
		"requestId": "req-004",
		"userId":    "user-202",
		"ip":        "10.0.0.5",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "WARN",
		"message":   "User not found during login",
		"requestId": "req-005",
		"userId":    "unknown",
		"ip":        "172.16.0.3",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "DEBUG",
		"message":   "Password validation started",
		"requestId": "req-006",
		"userId":    "user-202",
		"ip":        "10.0.0.5",
		"timestamp": "",
	},
	{
		"service":   "auth-service",
		"level":     "ERROR",
		"message":   "Suspicious login activity detected",
		"requestId": "req-007",
		"userId":    "user-303",
		"ip":        "203.0.113.99",
		"timestamp": "",
	},
}
