package main

var MockPaymentLog = []map[string]interface{}{
	{
		"service":    "payment-service",
		"level":      "INFO",
		"message":    "Payment initiated",
		"request_id": "req-201",
		"order_id":   "order-1001",
		"payment_id": "pay-2001",
		"gateway":    "Razorpay",
		"amount":     1499.99,
		"timestamp":  "",
	},
	{
		"service":    "payment-service",
		"level":      "DEBUG",
		"message":    "Calling payment gateway API",
		"request_id": "req-202",
		"order_id":   "order-1002",
		"payment_id": "pay-2001",
		"gateway":    "Razorpay",
		"amount":     1499.99,
		"timestamp":  "",
	},
	{
		"service":    "payment-service",
		"level":      "WARN",
		"message":    "Payment delayed due to network latency",
		"request_id": "req-203",
		"order_id":   "order-1004",
		"payment_id": "pay-2002",
		"gateway":    "Stripe",
		"amount":     799.00,
		"timestamp":  "",
	},
	{
		"service":    "payment-service",
		"level":      "ERROR",
		"message":    "Payment failed due to insufficient funds",
		"request_id": "req-204",
		"order_id":   "order-1005",
		"payment_id": "pay-2003",
		"gateway":    "Stripe",
		"amount":     3299.00,
		"timestamp":  "",
	},
	{
		"service":    "payment-service",
		"level":      "INFO",
		"message":    "Payment completed successfully",
		"request_id": "req-205",
		"order_id":   "order-1006",
		"payment_id": "pay-2004",
		"gateway":    "PayU",
		"amount":     2499.50,
		"timestamp":  "",
	},
}
