package main

var MockOrderLog = []map[string]interface{}{
	{
		"service":    "order-service",
		"level":      "INFO",
		"message":    "Order created successfully",
		"request_id": "req-101",
		"user_id":    "user-101",
		"order_id":   "order-1001",
		"product_id": "prod-501",
		"stock_left": 10,
		"carrier":    "BlueDart",
		"timestamp":  "",
	},
	{
		"service":    "order-service",
		"level":      "DEBUG",
		"message":    "Inventory check started",
		"request_id": "req-102",
		"user_id":    "user-102",
		"order_id":   "order-1001",
		"product_id": "prod-501",
		"stock_left": 10,
		"carrier":    "FedEx",
		"timestamp":  "",
	},
	{
		"service":    "order-service",
		"level":      "WARN",
		"message":    "Low stock detected",
		"request_id": "req-103",
		"user_id":    "user-103",
		"order_id":   "order-1002",
		"product_id": "prod-501",
		"stock_left": 3,
		"carrier":    "DHL",
		"timestamp":  "",
	},
	{
		"service":    "order-service",
		"level":      "ERROR",
		"message":    "Order failed due to insufficient stock",
		"request_id": "req-104",
		"user_id":    "user-104",
		"order_id":   "order-1003",
		"product_id": "prod-999",
		"stock_left": 0,
		"carrier":    "FedEx",
		"timestamp":  "",
	},
	{
		"service":    "order-service",
		"level":      "INFO",
		"message":    "Order shipped successfully",
		"request_id": "req-105",
		"user_id":    "user-105",
		"order_id":   "order-1004",
		"product_id": "prod-502",
		"stock_left": 7,
		"carrier":    "BlueDart",
		"timestamp":  "",
	},
}
